### PR TITLE
Added new colour theme according to logo and shadow effect

### PR DESCRIPTION
**Pull request by devarshidoshi**

### CODE REVIEW

**Comment by devarshidoshi** [comment]
Or else you can just label my PR as hacktober-accepted 
image

**Comment by devarshidoshi** [comment]
Waiting For Your Response....

**Review by velitasali — APPROVED** [review]
Looks nice. I don't see a problem with it.

**Comment by devarshidoshi** [comment]
Thanks A Lot For Approval.

**Pull request merged**
