### PR TITLE
refactor: Update landing page

### PR DESCRIPTION
**Pull request by ptanmay143**
Please verify the changes in `index.html` file. The other changed files in the commit are mostly deleted items.
- Complete the feature set of TrebleShot.
- Add 7 screenshots of the application for now.
- Add statistics for Play Store downloads, GitHub stars and issues.
- Remove components from the page that are currently not required.
- Remove the redundant images from repository.
- Add F-Droid link in the important links section.

### CODE REVIEW

**Comment by ptanmay143** [comment]
View live at https://ptanmay143.github.io/trebleshot.github.io/

**Comment by velitasali** [comment]
Hey, thank you for working on this. The landing page seems to be in need of a background. We have some artworks here: https://github.com/genonbeta/TrebleShot/tree/master/assets/artwork

Or I might be wrong. The white background doesn't look like it blends in.

Other than that, this can be used to improve upon and be merged.

**Comment by ptanmay143** [comment]
You're absolutely right. I didn't notice the white background as I use my browser with Dark Reader extension. I will add a suitable background to the page from your suggestions.

**Comment by ptanmay143** [comment]
Fixed the issue of no background image.

**Comment by velitasali** [comment]
This looks better. Also, the new background is very nice. Thanks.

**Comment by ptanmay143** [comment]
Are you going to merge these 2 commits?

**Comment by velitasali** [comment]
@ptanmay143 I can If you have no incoming commits.

**Comment by ptanmay143** [comment]
No, for now. this much only

**Pull request merged**
